/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { School } from "./School";
import { SchoolCountArgs } from "./SchoolCountArgs";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolFindUniqueArgs } from "./SchoolFindUniqueArgs";
import { DeleteSchoolArgs } from "./DeleteSchoolArgs";
import { SchoolService } from "../school.service";
@graphql.Resolver(() => School)
export class SchoolResolverBase {
  constructor(protected readonly service: SchoolService) {}

  async _schoolsMeta(
    @graphql.Args() args: SchoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [School])
  async schools(@graphql.Args() args: SchoolFindManyArgs): Promise<School[]> {
    return this.service.schools(args);
  }

  @graphql.Query(() => School, { nullable: true })
  async school(
    @graphql.Args() args: SchoolFindUniqueArgs
  ): Promise<School | null> {
    const result = await this.service.school(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => School)
  async deleteSchool(
    @graphql.Args() args: DeleteSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.deleteSchool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
